name: Add Label

on:
  issues:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.comment.body }}
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        #if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: bug
